---
- hosts: mcservers
  become: True
  roles:
    - role: common
      tags: common
    - role: minecraft
      tags: minecraft
    - role: ssh
      tags: ssh
    - role: openjdk
      tags: openjdk
    - role: mackerel
      tags: mackerel
