---
- name: create mackerel dirs
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
    - { path: '{{ mackerel_agent_conf_dir }}', owner: 'root', group: 'root' }
  notify: restart mackerel-agent

- name: import mackerel apt key
  apt_key:
    url: "{{ mackerel_apt_key }}"
    state: present
  notify: restart mackerel-agent

- name: add mackerel repository
  apt_repository:
    repo: "deb [arch=amd64] {{ mackerel_apt_repo }} mackerel contrib"
    state: present
    filename: mackerel
  notify: restart mackerel-agent

- name: ensure mackerel-agent is installed
  apt:
    pkg: "{{ mackerel_agent_package }}"
    update_cache: True
    cache_valid_time: "{{ apt_cache_valid_time }}"
  notify: restart mackerel-agent

- name: define mackerel-agent configuration file
  template:
    src: mackerel-agent.conf.j2
    dest: "{{ mackerel_agent_conf_dir }}/mackerel-agent.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart mackerel-agent

- name: ensure mackerel-agent is started
  service:
    name: "{{ mackerel_agent_package }}"
    state: started
