---
- name: ensure common packages are installed
  apt:
    pkg: "{{ common_packages }}"
    update_cache: True
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: wheel group exist
  group:
    name: wheel
    gid: "11"
    state: present

- name: add groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ os_groups | default([]) }}"
  register: add_groups

- name: add users
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
  with_items: "{{ os_users }}"

- name: add users to appropriate group
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups | default('') }}"
    append: yes
  with_items: "{{ os_users }}"

- name: add admin to wheel group
  user:
    name: "{{ item.username }}"
    groups: wheel
    append: yes
  with_items: "{{ os_users }}"
  register: add_wheel_group
  when: item.is_admin | default(false)

- name: sudo configured
  copy:
    src: sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
  when: add_wheel_group is success

- name: su configured
  copy:
    src: su
    dest: /etc/pam.d/su
    owner: root
    group: root
    mode: 0644
  when: add_wheel_group is success

- name: sysctl.conf configured
  sysctl:
    name: "{{ item.k }}"
    value: "{{ item.v }}"
    state: present
    reload: yes
  with_items: "{{ sysctl_dict }}"

- name: ensure ufw is installed
  apt:
    pkg: ufw
    update_cache: True
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: ensure ufw is configured
  template:
    src: ufw.j2
    dest: /etc/default/ufw
    owner: root
    group: root
    mode: 0644
  notify: restart ufw

- name: configure ufw defaults
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify: restart ufw

- name: enable ufw logging
  ufw:
    logging: "on"
  notify: restart ufw

- name: ensure ufw always allows an ssh connection
  ufw:
    rule: limit
    port: "{{ ssh_port }}"
    proto: tcp
  notify: restart ufw

- name: enable ufw
  ufw:
    state: enabled
